apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oilmodweb
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: storybook
      src: "."
      dockerfileName: Dockerfile.stories
      publicPort: http
      ports:
        - name: http
          port: 80
  dnsAppAlias:
    environment: prod
    component: storybook
