name: Deploy Storybook
on:
  push:
    branches:
      - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build_Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build components
        run: node builder
      - name: Build storybook
        run: yarn build-storybook
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 './dist/storybook/*' 'https://topstorybook.blob.core.windows.net/$web/${{ secrets.SAS }}' --recursive
