name: Deploy Storybook
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build_Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm install
      - name: Build storybook
        run: npm run storybook:build
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 copy './dist/storybook/oilmod-web/*' 'https://topstorybook.blob.core.windows.net/$web/${{ secrets.SAS }}' --recursive
