name: Deploy Storybook
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build_Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: yarn
      - name: Build components
        run: node builder
      - name: Build storybook
        run: yarn build-storybook
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 copy './dist/storybook/*' 'https://topstorybook.blob.core.windows.net/$web/${{ secrets.SAS }}' --recursive
