name: Tests
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        run: yarn build-storybook
      - uses: actions/checkout@v2
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 --source './dist/storybook/*' --destination 'https://topstorybook.blob.core.windows.net/$web/' --dest-key ${{ secrets.STORAGE_KEY }} --recursive --set-content-type
