name: Run tests and linter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Every sunday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests & linting
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install deps
        run: npm install
      - uses: mansagroup/nrwl-nx-action@v2
        name: Run
        with:
          targets: test-all,lint-all
