name: Run tests and linter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Every sunday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests & linting
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test:all
      - name: Run linter
        run: npm run lint:all
