name: Run tests and linter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests & linting
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test:all
      - name: Run linter
        run: npm run lint:all
