name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: node test-all.js --ci
